#!/bin/bash

getprocs() {
 sudo netstat -plant | grep :::$1 | awk '{print $7}' | awk -F "/" '{print $2}' | xargs
}

if [ "$#" -ne 1 ]; then
	echo "Getting names of bound processes..."
	echo `getprocs`
else
	echo "Getting processes listening to "$1"..."
	PROCS=`getprocs $1`
	if [ -z "$PROCS" ]; then
		echo "No processes are bound to "$1
	else
		echo $PROCS
	fi
fi
