#!/bin/bash

subnet=$1

declare -a PIDS

for addr in `seq 0 1 255 `; do
	( ping -c 3 -t 5 192.168.$subnet.$addr > /dev/null 2>&1 &&
	echo 192.168.$subnet.$addr is ALIVE ) &
	PIDS[$addr]=$!
done

while [ ${#PIDS[@]} -gt 0 ]; do
	for PID in ${PIDS[@]}; do
		if ! kill -0 $PID > /dev/null 2>&1; then
			unset PIDS[$PID]
		fi
	done
done
